const mongoose = require("mongoose");
const AgeNashnalitySchema = mongoose.Schema(
  {
 
    application_type:{type:String},
    status:{type:String},
    createdBy:{type:String},
    createdByName:{type:String},
    Data:{
    docName: { type: String },
    statusfname: { type: String },
    fullName_English: { type: String },
    fullName_Marathi: { type: String },
    fatherName_english: { type: String },
    fatherName_marathi: { type: String },
    BirthDate: { type: String },
    age: { type: Number },
    Gender: { type: String },
    work_type: { type: String },
    phoneNUm: { type: Number },
    email: { type: String },
    AdharNo: { type: String },
    address: { type: String },
    Building: { type: String },
    street: { type: String },
    // depart: { type: String },
    landmark: { type: String },
    district: { type: String },
    taluka: { type: String },
    village: { type: String },
    pincode: { type: Number },
    onAddressLiveing: { type: Number },
    currentlivingInyear: { type: String },
    Applicunt_Live_In_MH_Inyear: { type: String },
    relationApplicant_beneficiary: { type: String },
    benificiary_NameStatus: { type: String },
    benificiary_Name: { type: String },
    benificiary_DOB: { type: String },
    Benificiary_Phoneno: { type: String },
    // BirthDetails: { type: Boolean },
    BirthDetails_address: { type: String },
    BirthDetails_streetName: { type: String },
    BirthDetails_Building: { type: String },
    BirthDetails_locality: { type: String },
    BirthDetails_Country: { type: String },
    BirthDetails_state: { type: String },
    BirthDetails_district: { type: String },
    BirthDetails_tehsil: { type: String },
    BirthDetails_village: { type: String },
    BirthDetails_pincode: { type: Number },
    // isMovablePropartyOfApp_FAther_Hus: { type: Boolean },
    Proparty_address: { type: String },
    Proparty_street: { type: String },
    Proparty_Building: { type: String },
    Proparty_locality: { type: String },
    Proparty_Country: { type: String },
    Proparty_State: { type: String },
    Proparty_district: { type: String },
    Proparty_Tehsil: { type: String },
    Proparty_village: { type: String },
    Proparty_pincode: { type: Number },
    Benificiary_propartyHolder_Relation: { type: String },
    Benificiary_propartyDetails: { type: String },
    Benificiary_Father_HusRecidance: { type: String },
    Benificiary_FatherRecidaceOfBirth: { type: String },
    isBenificiary_FatherRecidaceOfBirth_outOf_MH: { type: String },
    placeOfEmploment: { type: String },
    isApllicantBenificiaryOtherState: { type: Boolean },
    ApllicantBenificiaryOtherState: { type: String },
    ApllicantBenificiaryOtherState_district: { type: String },
    ApllicantBenificiaryOtherState_Taluka: { type: String },
    ApllicantBenificiaryOtherState_Village: { type: String },
    ApllicantBenificiaryOtherState_pincode: { type: Number },
    CertificateReason: { type: String },
    formPrice :{type: Number}
  },
    EducationDetailsArray:{type:Array},
    MigrationBeneficiaryArray:{type:Array},
    FMemberBeneficiaryArray:{type:Array},
    note:{type:String},
    isNew:{type:Boolean,default:true},
    rejNote:{type:String},
    subNote:{type:String},
    compNote:{type:String},
    
    //uploads
    acknowledgmentDocument:{type:String},
    finalDocument:{type:String},
   reshanCard :{type:String},
   adharCard :{type:String},
   lightBill :{type:String},
   schoolLeaveCertificate :{type:String},
   taxBillOr15yerOldLightbill :{type:String},
   photo :{type:String},
   selfDeclaration:{type:String},

  },
  { timestamps: true }
);
module.exports = mongoose.model("AgeNashnality", AgeNashnalitySchema);
