const mongoose = require("mongoose");
const AgeNashnalitySchema = mongoose.Schema(
  {
    docName: { type: String },
    statusfname: { type: String },
    fullName_English: { type: String },
    fullName_Marathi: { type: String },
    fatherName_english: { type: String },
    fatherName_marathi: { type: String },
    BirthDate: { type: String },
    age: { type: Number },
    Gender: { type: String },
    work_type: { type: String },
    phoneNUm: { type: Number },
    email: { type: String },
    AdharNo: { type: String },
    Building: { type: String },
    address: { type: String },
    strateName: { type: String },
    depart: { type: String },
    landmark: { type: String },
    district: { type: String },
    taluka: { type: String },
    village: { type: String },
    pincode: { type: Number },
    onAddressLiveing: { type: Number },
    currentlivingInyear: { type: String },
    Applicunt_Live_In_MH_Inyear: { type: Number },
    applicant_Name: { type: String },
    benificiary_NameStatus: { type: String },
    benificiary_Name: { type: String },
    benificiary_DOB: { type: String },
    Benificiary_Phoneno: { type: String },
    BirthDetails: { type: Boolean },
    BirthDetails_address: { type: String },
    BirthDetails_strateName: { type: String },
    BirthDetails_Building: { type: String },
    BirthDetails_depart: { type: String },
    BirthDetails_Country: { type: String },
    BirthDetails_district: { type: String },
    BirthDetails_taluka: { type: String },
    BirthDetails_village: { type: String },
    BirthDetails_pincode: { type: Number },
    BenificiaryEdgucationDetails: [
      {
        begree: { type: String },
        organizationName: { type: String },
        AddmisionYear: { type: Number },
        leaveYear: { type: Number },
        EducationPlace: { type: String },
      },
    ],
    migration_MH_From_Another_State: { type: Boolean },
    migration: [
      {
        migrationToMHYear: { type: Number },
        BeforeMigrationLocation: { type: String },
        reasonOfMigration: { type: String },
        placeOfMigration: { type: String },
        MigrationStartYear: { type: Number },
        MigrationEndYear: { type: Number },
      },
    ],
    isMovablePropartyOfApp_FAther_Hus: { type: Boolean },
    Proparty_address: { type: String },
    Proparty_street: { type: String },
    Proparty_Building: { type: String },
    Proparty_locality: { type: String },
    Proparty_Country: { type: String },
    Proparty_State: { type: String },
    Proparty_district: { type: String },
    Proparty_Tehsil: { type: String },
    Proparty_village: { type: String },
    Proparty_pincode: { type: Number },
    Benificiary_propartyHolder_Relation: { type: String },
    Benificiary_propartyDetails: { type: String },
    Benificiary_Father_HusRecidance: { type: String },
    Benificiary_FatherRecidaceOfBirth: { type: String },
    isBenificiary_FatherRecidaceOfBirth_outOf_MH: { type: String },
    placeOfEmploment: { type: String },
    isApllicantBenificiaryOtherState: { type: Boolean },
    ApllicantBenificiaryOtherState: { type: Boolean },
    ApllicantBenificiaryOtherState_district: { type: Boolean },
    ApllicantBenificiaryOtherState_Taluka: { type: Boolean },
    ApllicantBenificiaryOtherState_Village: { type: Boolean },
    ApllicantBenificiaryOtherState_pincode: { type: Number },
    CertificateReason: { type: String },
    //docs

  },
  { timestamps: true }
);
module.exports = mongoose.model("AgeNashnality", AgeNashnalitySchema);
