const mongoose = require("mongoose");

const formPrice = mongoose.Schema(
  {
    userID:{type:String},
    shopActNew:{type:Number},
    shopActReNew: { type: Number },
    udhamAbhar: { type: Number },
    companyGST: { type: Number },
    rentAgreement: { type: Number },
    individualGST: { type: Number },
    foodLicense1year: { type: Number },
    foodLicense2year: { type: Number },
    foodLicense3year: { type: Number },
    eGazette_OpenOBC: { type: Number },
    eGazette_SC: { type: Number },
    eGazette_SBC: { type: Number },
    eGazette_ST: { type: Number },
    eGazette_VJ: { type: Number },
    eGazette_NT: { type: Number },
    passport_Normal: { type: Number },
    passport_Tatkal: { type: Number },
    learningDl_MCWOG: { type: Number },
    learningDl_MCWG: { type: Number },
    learningDl_LMV: { type: Number },
    learningDl_LMV_TR: { type: Number },
    learningDl_MCWOG_MCWG: { type: Number },
    learningDl_MCWOG_LMV: { type: Number },
    learningDl_MCWG_LMV: { type: Number },
    learningDl_MCWOG_MCWG_LMV: { type: Number },
    learningDl_MCWG_LMVTR: { type: Number },
    learningDl_MCWOG_LMVTR: { type: Number },
    learningDl_MCWOG_MCWG_LMV_TR: { type: Number },
    permanent_MCWOG: { type: Number },
    permanent_MCWG: { type: Number },
    permanent_LMV: { type: Number },
    permanent_LMV_TR: { type: Number },
    permanent_MCWOG_MCWG: { type: Number },
    permanent_MCWOG_LMV: { type: Number },
    permanent_MCWG_LMV: { type: Number },
    permanent_MCWOG_MCWG_LMV: { type: Number },
    permanent_MCWG_LMVTR: { type: Number },
    permanent_MCWOG_LMVTR: { type: Number },
    permanent_MCWOG_MCWG_LMV_TR: { type: Number },
    renew_MCWOG: { type: Number },
    renew_MCWG: { type: Number },
    renew_LMV: { type: Number },
    renew_LMV_TR: { type: Number },
    renew_MCWOG_MCWG: { type: Number },
    renew_MCWOG_LMV: { type: Number },
    renew_MCWG_LMV: { type: Number },
    renew_MCWOG_MCWG_LMV: { type: Number },
    renew_MCWG_LMVTR: { type: Number },
    renew_MCWOG_LMVTR: { type: Number },
    renew_MCWOG_MCWG_LMV_TR: { type: Number },
    panCard: { type: Number },
    voterCard: { type: Number },
    isNew:{type:Boolean,default:true},


  },
  { timestamps: true }
);

module.exports = mongoose.model("formPrice", formPrice);
