const mongoose = require("mongoose");
const UdhamAdharSchema = mongoose.Schema({
  application_type:{type:String},
  status:{type:String},
  createdBy:{type:String},
  createdByName:{type:String},
  Title: { type: String},
  Owner_Name: { type: String},
  PAN_Card: { type: String},
  Adhar_Card_no: { type: String},
  GST_Number: { type: String },
  Social_Category: { type: String},
  Gender :{type:String},
  Shop_Name: { type: String},
  Mobile_Number: { type: Number },
  email: { type: String},
  Number_of_Employee: { type: Number },
  Business_Started_Date: { type: String},
  Shop_Address: { type: String},
  Nature_Of_Business: { type: String},
  Investment_Rs: { type: Number },
  Bank_Name: { type: String},
  Bank_Account_Number: { type: Number },
  Bank_IFSC_Code: { type: String},
  formPrice :{type: Number},
  retailerName:{type:String},
  note:{type:String},
  isNew:{type:Boolean,default:true},
  rejNote:{type:String},
  subNote:{type:String},
  compNote:{type:String},

  //uploads
  acknowledgmentDocument:{type:String},
  finalDocument:{type:String},
  Aadhar_Upload_Card: { type: String},
  Pan_Upload_Card: { type: String },
  Passport: { type: String },
  Bank_Upload_Passbook: { type: String},
});
module.exports=mongoose.model('udhamadhar',UdhamAdharSchema)
